# Generated by Django 3.2.25 on 2024-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Guide', 'Guide'), ('Visiting Professor', 'Visiting Professor'), ('Post-Doc Student', 'Post-Doc Student'), ('Ph.D. Student', 'Ph.D. Student'), ('M.S. Student', 'M.S. Student')], max_length=50)),
                ('photo', models.ImageField(upload_to='members/')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
