# Generated by Django 5.0.6 on 2024-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_mtechstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thesis_title', models.CharField(max_length=500)),
                ('intern_duration', models.CharField(max_length=100)),
                ('additional_info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
