# Generated by Django 5.0.6 on 2024-06-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_member'),
        ('mainApp', '0004_visitingstudent'),
    ]

    operations = [
    ]
