# Generated by Django 5.0.6 on 2024-06-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_merge_0003_member_0004_visitingstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardWinningPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
