# Generated by Django 5.0.6 on 2024-06-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_editedbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=255)),
                ('publication_date', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
            ],
        ),
    ]
