# Generated by Django 5.0.6 on 2024-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
