# Generated by Django 3.2.25 on 2024-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
