# Generated by Django 5.0.6 on 2024-06-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_member_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalpapers',
            name='award',
        ),
        migrations.RemoveField(
            model_name='journalpapers',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='journalpapers',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='journalpapers',
            name='volume',
        ),
    ]
