# Generated by Django 5.0.6 on 2024-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_remove_bookchapters_award_bookchapters_chapter_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapters',
            name='editors',
        ),
        migrations.AddField(
            model_name='bookchapters',
            name='book_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
