# Generated by Django 5.0.6 on 2024-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_remove_bookchapters_editors_bookchapters_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('conference', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CoferencePapers',
        ),
    ]
