# Generated by Django 5.0.6 on 2024-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_conferencepaper_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='is_granted',
            field=models.BooleanField(default='False'),
        ),
    ]
